[[entries]]
id = "5be79248-7b86-465d-953c-d0c69ab64e8a"
type = "improvement"
description = "Implement support for NumPy-style docstrings"
author = "celsiusnarhwal"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/279"
issues = ["https://github.com/celsiusnarhwal/pydoc-markdown/issues/251"]

[[entries]]
id = "4409675c-ea67-4c56-be5a-a7310f779c15"
type = "improvement"
description = "Change `PythonLoader.encoding` default value from `None` (system default) to `utf-8`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/282"

[[entries]]
id = "cbec74c9-4d3f-4c65-9d57-73d024ce17fa"
type = "improvement"
description = "Bump minimum version of `databind.core` and `databind.json` to `^4.4.2` to ensure Python 3.12 support"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/304"

[[entries]]
id = "5e25fdde-ec38-42a7-9ab1-7066e4af6d81"
type = "breaking change"
description = "Drop Python 3.7 compatibility"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/304"

[[entries]]
id = "78a8f6a1-eaaa-41cf-89f0-e746ddb42491"
type = "fix"
description = "Fix `escape_except_blockquotes` option for greater than 9 blockquotes in a docstring"
author = "@jackgerrits"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/317"
